In [1]:
#Importing Libraries

import numpy as np #To handle Mathematical calculations
import matplotlib.pyplot as plt #To plot charts 
%matplotlib inline
import pandas as pd #TO import and manage datasets
import glob
import os
import warnings
# pd.set_option('display.max_columns', None)  
# pd.set_option('display.max_rows', None)  

#Disable warning messages
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
#Combining All Offensive Data
path = r'../Datasets/Whoscored/Player-Stats'
folder = glob.glob(path + "/*Offensive*.csv")

li = []

for file in folder:
    individualOffensivePlayerDataframe = pd.read_csv(file)
    league = os.path.basename(file).split('-')[0]
    season = os.path.basename(file).split('-')[2]
    individualOffensivePlayerDataframe['League'] = league
    individualOffensivePlayerDataframe['Season'] = season
    for index, row in individualOffensivePlayerDataframe.iterrows():
        age = int(row["Age"]) - (2018-int(row["Season"]))
        individualOffensivePlayerDataframe.set_value(index, 'Age', age)
        
        #Cleaning Apps column
        if '(' in row["Apps"] :
            apps = int(row["Apps"].split("(")[0])
            individualOffensivePlayerDataframe.set_value(index, 'Apps', apps)
        else :
            apps = int(row["Apps"])
            individualOffensivePlayerDataframe.set_value(index, 'Apps', apps)
            
        #Cleaning Position column
        if ',' in row["Position"]:
            primary = row["Position"].split(",")[0]
            if '(' in primary:
                primary = primary.split("(")[0]
                individualOffensivePlayerDataframe.set_value(index, 'Position', primary)
            else:
                individualOffensivePlayerDataframe.set_value(index, 'Position', primary)
        elif '(' in row["Position"]:
            primary = row["Position"].split("(")[0]
            individualOffensivePlayerDataframe.set_value(index, 'Position', primary)
            
    li.append(individualOffensivePlayerDataframe)

combinedOffensivePlayerDataframe = pd.concat(li)

In [3]:
#Combining All Defensive Data
path = r'../Datasets/Whoscored/Player-Stats'
folder = glob.glob(path + "/*Defensive*.csv")

li = []

for file in folder:
    individualDefensivePlayerDataframe = pd.read_csv(file)
    league = os.path.basename(file).split('-')[0]
    season = os.path.basename(file).split('-')[2]
    individualDefensivePlayerDataframe['League'] = league
    individualDefensivePlayerDataframe['Season'] = season
    for index, row in individualDefensivePlayerDataframe.iterrows():
        age = int(row["Age"]) - (2018-int(row["Season"]))
        individualDefensivePlayerDataframe.set_value(index, 'Age', age)
        
        #Cleaning Apps column
        if '(' in row["Apps"] :
            apps = int(row["Apps"].split("(")[0])
            individualDefensivePlayerDataframe.set_value(index, 'Apps', apps)
        else :
            apps = int(row["Apps"])
            individualDefensivePlayerDataframe.set_value(index, 'Apps', apps)
            
        #Cleaning Position column  
        if ',' in row["Position"]:
            primary = row["Position"].split(",")[0]
            if '(' in primary:
                primary = primary.split("(")[0]
                individualDefensivePlayerDataframe.set_value(index, 'Position', primary)
            else:
                individualDefensivePlayerDataframe.set_value(index, 'Position', primary)
        elif '(' in row["Position"]:
            primary = row["Position"].split("(")[0]
            individualDefensivePlayerDataframe.set_value(index, 'Position', primary)
    
    li.append(individualDefensivePlayerDataframe)

combinedDefensivePlayerDataframe = pd.concat(li)

In [4]:
#Combining All Passing Data
path = r'../Datasets/Whoscored/Player-Stats'
folder = glob.glob(path + "/*Passing*.csv")

li = []

for file in folder:
    individualPassingPlayerDataframe = pd.read_csv(file)
    league = os.path.basename(file).split('-')[0]
    season = os.path.basename(file).split('-')[2]
    individualPassingPlayerDataframe['League'] = league
    individualPassingPlayerDataframe['Season'] = season
    for index, row in individualPassingPlayerDataframe.iterrows():
        age = int(row["Age"]) - (2018-int(row["Season"]))
        individualPassingPlayerDataframe.set_value(index, 'Age', age)
        
        #Cleaning Apps column
        if '(' in row["Apps"] :
            apps = int(row["Apps"].split("(")[0])
            individualPassingPlayerDataframe.set_value(index, 'Apps', apps)
        else :
            apps = int(row["Apps"])
            individualPassingPlayerDataframe.set_value(index, 'Apps', apps)
           
        #Cleaning Position column
        if ',' in row["Position"]:
            primary = row["Position"].split(",")[0]
            if '(' in primary:
                primary = primary.split("(")[0]
                individualPassingPlayerDataframe.set_value(index, 'Position', primary)
            else:
                individualPassingPlayerDataframe.set_value(index, 'Position', primary)
        elif '(' in row["Position"]:
            primary = row["Position"].split("(")[0]
            individualPassingPlayerDataframe.set_value(index, 'Position', primary)
    
    li.append(individualPassingPlayerDataframe)

combinedPassingPlayerDataframe = pd.concat(li)

In [5]:
#Combining All Summary Data
path = r'../Datasets/Whoscored/Player-Stats'
folder = glob.glob(path + "/*Summary*.csv")

li = []

for file in folder:
    individualSummaryPlayerDataframe = pd.read_csv(file)
    league = os.path.basename(file).split('-')[0]
    season = os.path.basename(file).split('-')[2]
    individualSummaryPlayerDataframe['League'] = league
    individualSummaryPlayerDataframe['Season'] = season
    for index, row in individualSummaryPlayerDataframe.iterrows():
        age = int(row["Age"]) - (2018-int(row["Season"]))
        individualSummaryPlayerDataframe.set_value(index, 'Age', age)
        
        #Cleaning Apps column
        if '(' in row["Apps"] :
            apps = int(row["Apps"].split("(")[0])
            individualSummaryPlayerDataframe.set_value(index, 'Apps', apps)
        else :
            apps = int(row["Apps"])
            individualSummaryPlayerDataframe.set_value(index, 'Apps', apps)
            
        #Cleaning Position column    
        if ',' in row["Position"]:
            primary = row["Position"].split(",")[0]
            if '(' in primary:
                primary = primary.split("(")[0]
                individualSummaryPlayerDataframe.set_value(index, 'Position', primary)
            else:
                individualSummaryPlayerDataframe.set_value(index, 'Position', primary)
        elif '(' in row["Position"]:
            primary = row["Position"].split("(")[0]
            individualSummaryPlayerDataframe.set_value(index, 'Position', primary)
            
    
    li.append(individualSummaryPlayerDataframe)

combinedSummaryPlayerDataframe = pd.concat(li)

In [6]:
#combining all the DFs'
combinedPlayerDataframe = pd.concat([combinedOffensivePlayerDataframe, combinedDefensivePlayerDataframe, combinedPassingPlayerDataframe, combinedSummaryPlayerDataframe], axis=1)

#Removing suplicates
combinedPlayerDataframe = combinedPlayerDataframe.loc[:,~combinedPlayerDataframe.columns.duplicated()]

#Removing players who have played less than 10 games in last season
minimum_number_of_games_played = 10
combinedPlayerDataframe = combinedPlayerDataframe[combinedPlayerDataframe.Apps >= minimum_number_of_games_played]

#Replace '-' with 0
combinedPlayerDataframe = combinedPlayerDataframe.replace('-', 0)

In [7]:
# combinedPlayerDataframe.Apps.tolist()

In [8]:
#Selecting only the needed columns for the forecasting process

allPlayers = combinedPlayerDataframe[['Name', 'Season', 'Rating', 'Age']]
allPlayers = allPlayers[allPlayers['Season'].notnull()].copy()
allPlayers['Season'] = allPlayers['Season'].astype(int)
allPlayers

                   Name  Season  Rating  Age
0          Arjen Robben    2009    8.18   26
1       Stefan Kießling    2009    7.79   26
2    Zvjezdan Misimovic    2009    7.74   28
3            Edin Dzeko    2009    7.73   24
4       Claudio Pizarro    2009    7.63   31
..                  ...     ...     ...  ...
455     Frederic Veseli    2018    6.29   26
457       Joel Campbell    2018    6.29   27
459   Francesco Zampano    2018    6.28   25
480       Massimo Gobbi    2018    6.20   38
493      Fabio Ceravolo    2018    6.18   32

[17791 rows x 4 columns]

In [9]:
#Store a list of all the players
nameList = allPlayers.Name.unique()

#create a dataframe just to store the mean values of player rating's 
meanDf = pd.DataFrame(columns=['Mean'])

#Calculating career growth and rating avergae of every player (Feature engineering)
for name in nameList:
    mean = allPlayers.loc[allPlayers.Name == name]['Rating'].mean()
    length = len(allPlayers.loc[allPlayers.Name == name]['Rating'])
    growth = allPlayers.loc[allPlayers.Name == name]['Rating'].tolist()[length-1] - allPlayers.loc[allPlayers.Name == name]['Rating'].tolist()[0]
    meanDf.set_value(name, 'Name', name)
    meanDf.set_value(name, 'Mean', mean)
    meanDf.set_value(name, 'Growth', growth)
    
#Merging all the data together   
allPlayers = pd.merge(allPlayers, meanDf, on=['Name'])

#Converting column type
allPlayers['Mean'] = allPlayers['Mean'].astype(np.float64)

In [10]:
allPlayers.loc[allPlayers.Name == 'Lionel Messi']

              Name  Season  Rating  Age   Mean  Growth
5242  Lionel Messi    2009    8.67   23  8.641   -0.19
5243  Lionel Messi    2010    8.76   24  8.641   -0.19
5244  Lionel Messi    2011    8.88   25  8.641   -0.19
5245  Lionel Messi    2012    8.83   26  8.641   -0.19
5246  Lionel Messi    2013    8.34   27  8.641   -0.19
5247  Lionel Messi    2014    8.84   28  8.641   -0.19
5248  Lionel Messi    2015    8.46   29  8.641   -0.19
5249  Lionel Messi    2016    8.47   30  8.641   -0.19
5250  Lionel Messi    2017    8.68   31  8.641   -0.19
5251  Lionel Messi    2018    8.48   32  8.641   -0.19

In [11]:
#Another portion of feature engineering

from pandas import Series
from pandas import DataFrame
from pandas import concat

allPlayers = allPlayers.sort_values(['Season', 'Name'])

#Creating 2 new features for every player by combining both the last season rating and the difference between that and the
#~previous season rating

transformedPlayerDf = allPlayers.copy()
transformedPlayerDf['Last_Season_Rating'] = transformedPlayerDf.groupby(['Name'])['Rating'].shift()
transformedPlayerDf['Last_Season_Diff'] = transformedPlayerDf.groupby('Name')['Last_Season_Rating'].transform(Series.diff)
transformedPlayerDf = transformedPlayerDf.dropna()
transformedPlayerDf.head()

,Name,Season,Rating,Age,Mean,Growth,Last_Season_Rating,Last_Season_Diff
10247,Abdoulrazak Boukari,2010,6.84,24,6.840000,0.09,6.93,0.18
15778,Alessandro Matri,2010,6.79,26,6.713750,-0.58,6.92,-0.06
1643,Anderson,2010,6.95,23,6.806667,0.79,6.16,-0.68
992,Andrea Barzagli,2010,7.27,30,6.971111,-0.08,6.86,0.16
15003,Andrea Ranocchia,2010,7.16,23,7.157778,-0.22,7.48,0.17

In [12]:
#Forecasting using linear regression

from statistics import mean 
from sklearn import linear_model 

from sklearn.model_selection import cross_val_score
from sklearn import model_selection

accuracy = []

#For every season using previous season data to forecast current season rating
for season in range(2015,2019):
    
    training_set = transformedPlayerDf[transformedPlayerDf['Season'] == season-1]
    testing_set = transformedPlayerDf[transformedPlayerDf['Season'] == season]

    X_train = training_set.drop(['Rating', 'Name', 'Season'], axis=1)
    y_train = training_set['Rating'].values
    X_test = testing_set.drop(['Rating', 'Name', 'Season'], axis=1)
    y_test = testing_set['Rating'].values

    lin_reg = linear_model.LinearRegression(n_jobs=-1) 
    
    lin_reg.fit(X_train, y_train)

    #using k-folds cross validation for calculating forecast accuracy
    scores = cross_val_score(lin_reg, X_test, y_test, cv=10)
    accuracy.append(scores.mean())
     
print('Average accuracy for forecasting player ratings between 2015-2018: ' + "{:.2f}".format(mean(accuracy)*100) + "%")

Average accuracy for forecasting player ratings between 2015-2018: 66.52%

In [13]:
#Forecasting player ratings between 2019-2022

for season in range(2017, 2021):
    
    previousPlayers = allPlayers.loc[allPlayers.Season == season].copy()
    currentPlayers = allPlayers.loc[allPlayers.Season == season+1].copy()
    futurePlayers = currentPlayers.copy()

    futurePlayers['Season'] = currentPlayers['Season'].values+1
    futurePlayers['Age'] = currentPlayers['Age'].values+1

    futurePlayers.drop(['Rating'], axis=1)

    li = []
    li.append(previousPlayers)
    li.append(currentPlayers)
    li.append(futurePlayers)

    combinedDf = pd.concat(li)
    
    combinedDf = combinedDf.sort_values(['Season', 'Name'])

    transformedPlayerDf = combinedDf.copy()
    transformedPlayerDf['Last_Season_Rating'] = transformedPlayerDf.groupby(['Name'])['Rating'].shift()
    transformedPlayerDf['Last_Season_Diff'] = transformedPlayerDf.groupby('Name')['Last_Season_Rating'].transform(Series.diff)
    transformedPlayerDf = transformedPlayerDf.dropna()
    
    transformedPlayerDf = transformedPlayerDf.loc[transformedPlayerDf['Season'] == season+2]
    
    currentSeasonDf = transformedPlayerDf.drop(['Rating', 'Name', 'Season'], axis=1)
    y_pred = lin_reg.predict(currentSeasonDf)

    #Attaching the predicted values to the original DF so that the cycle can continue 
    #~until the forecasting range comes to an end 
    ratings = ["{:.2f}".format(value) for value in y_pred.tolist()]
    transformedPlayerDf['Rating'] = ratings
    transformedPlayerDf = transformedPlayerDf[['Name', 'Season', 'Rating', 'Age', 'Mean', 'Growth']]
    allPlayers = allPlayers.append(transformedPlayerDf)
    allPlayers = allPlayers[allPlayers['Rating'].notnull()].copy()
    allPlayers['Rating'] = allPlayers['Rating'].astype(float)

In [14]:
allPlayers.loc[allPlayers.Name == 'Kylian Mbappé']

                Name  Season  Rating  Age      Mean  Growth
12143  Kylian Mbappé    2016    7.22   18  7.586667    0.78
12144  Kylian Mbappé    2017    7.54   19  7.586667    0.78
12145  Kylian Mbappé    2018    8.00   20  7.586667    0.78
12145  Kylian Mbappé    2019    7.78   21  7.586667    0.78
12145  Kylian Mbappé    2020    7.69   22  7.586667    0.78
12145  Kylian Mbappé    2021    7.72   23  7.586667    0.78
12145  Kylian Mbappé    2022    7.73   24  7.586667    0.78

In [15]:
allPlayers.loc[(allPlayers.Season == 2018) & ((allPlayers.Age == 24) | (allPlayers.Age == 25))]

                    Name  Season  Rating  Age      Mean  Growth
12366    Abdoulaye Touré    2018    6.85   25  6.895000   -0.09
2101   Abdul Rahman Baba    2018    6.90   24  6.975000   -0.13
4129          Adam Maher    2018    7.47   25  7.162500    0.74
15213        Adam Masina    2018    6.66   25  6.872500    0.21
3508         Adam Zrelák    2018    6.42   25  6.420000    0.00
...                  ...     ...     ...  ...       ...     ...
3114      Yussuf Poulsen    2018    7.27   25  6.986667    0.26
3513           Yuya Kubo    2018    6.31   25  6.310000    0.00
17612          Ádám Nagy    2018    6.38   24  6.460000   -0.16
8683       Álvaro Medrán    2018    6.53   25  6.496667    0.01
8841        Ángel Correa    2018    6.68   24  6.766667   -0.09

[337 rows x 6 columns]

In [16]:
#write the DF to a csv file
allPlayers.to_csv('Forecasted Ratings 2019-2022.csv', index = False)