# Analyzing League Data

In [47]:
#Importing Libraries
import numpy as np #To handle Mathematical calculations
import matplotlib.pyplot as plt #To plot charts 
%matplotlib inline
import pandas as pd #TO import and manage datasets
import glob
import os

In [48]:
# path = r'C:\Projects\FYP\Datasets\Whoscored\Points-Table' # use your path
path = r'../Datasets/Whoscored/Points-Table' # use your path
folder = glob.glob(path + "/*.csv")

li = []

for file in folder:
#     df = pd.read_csv(filename, index_col=None, header=0)
    individualTeamDataframe = pd.read_csv(file)
    league = os.path.basename(file).split('-')[0]
    season = os.path.basename(file).split('-')[3]
    individualTeamDataframe['League'] = league
    individualTeamDataframe['Season'] = int(season)
    li.append(individualTeamDataframe)

# combinedDataframe = pd.concat(li, axis=0, ignore_index=True)
combinedTeamDataframe = pd.concat(li)

# dataset = pd.read_csv('C:\Projects\FYP\Datasets\Whoscored\Points-Table\LaLiga-Points-Table-2018-2019.csv')
# league = 'LaLiga'

In [49]:
combinedTeamDataframe.head()
# dataset['League'] = league
# dataset

,Rank,Team,Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points,League,Season
0,1,Bayern Munich,34,20,10,4,72,31,41,70,Bundesliga,2009
1,2,Schalke 04,34,19,8,7,53,31,22,65,Bundesliga,2009
2,3,Werder Bremen,34,17,10,7,71,40,31,61,Bundesliga,2009
3,4,Bayer Leverkusen,34,15,14,5,65,38,27,59,Bundesliga,2009
4,5,Borussia Dortmund,34,16,9,9,54,42,12,57,Bundesliga,2009

In [50]:
combinedTeamDataframe.shape

(1016, 12)

In [130]:
combinedTeamDataframe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1016 entries, 0 to 19
Data columns (total 12 columns):
Rank               1016 non-null int64
Team               1016 non-null object
Played             1016 non-null int64
Win                1016 non-null int64
Draw               1016 non-null int64
Loss               1016 non-null int64
Goals For          1016 non-null int64
Goals Against      1016 non-null int64
Goal Difference    1016 non-null int64
Points             1016 non-null int64
League             1016 non-null object
Season             1016 non-null int64
dtypes: int64(10), object(2)
memory usage: 103.2+ KB

In [133]:
laligaTeamDf = combinedTeamDataframe.loc[combinedTeamDataframe['League'] == 'LaLiga']
bundesligaTeamDf = combinedTeamDataframe.loc[combinedTeamDataframe['League'] == 'Bundesliga']
ligue1TeamDf = combinedTeamDataframe.loc[combinedTeamDataframe['League'] == 'Ligue1']
serieaTeamDf = combinedTeamDataframe.loc[combinedTeamDataframe['League'] == 'SerieA']
eplTeamDf = combinedTeamDataframe.loc[combinedTeamDataframe['League'] == 'PremierLeague']

# laliga2010Df = combinedDataframe.loc[(combinedDataframe['League'] == 'LaLiga') & (combinedDataframe['Season'] == '2010')]
# laliga2018Df = combinedDataframe.loc[(combinedDataframe['League'] == 'LaLiga') & (combinedDataframe['Season'] == '2018')]

In [132]:
laligaTeamDf

,Rank,Team,Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points,League,Season
0,1,Barcelona,38,31,6,1,98,24,74,99,LaLiga,2009
1,2,Real Madrid,38,31,3,4,102,35,67,96,LaLiga,2009
2,3,Valencia,38,21,8,9,59,40,19,71,LaLiga,2009
3,4,Sevilla,38,19,6,13,65,49,16,63,LaLiga,2009
4,5,Mallorca,38,18,8,12,59,44,15,62,LaLiga,2009
...,...,...,...,...,...,...,...,...,...,...,...,...
15,16,Real Valladolid,38,10,11,17,32,51,-19,41,LaLiga,2018
16,17,Celta Vigo,38,10,11,17,53,62,-9,41,LaLiga,2018
17,18,Girona,38,9,10,19,37,53,-16,37,LaLiga,2018
18,19,SD Huesca,38,7,12,19,43,65,-22,33,LaLiga,2018
19,20,Rayo Vallecano,38,8,8,22,41,70,-29,32,LaLiga,2018